In [1]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [3]:
df=pd.read_csv("data.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [7]:
import math
median_bedrooms=math.floor(df.bedrooms.median())
median_bedrooms

3

In [9]:
df.bedrooms=df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [11]:
reg=linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df['price'])


LinearRegression()

In [14]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [15]:
reg.intercept_

np.float64(383724.9999999998)

In [20]:
def variables(ar,bd,ag):
    return pd.DataFrame({'area':[ar],'bedrooms':[bd],'age':[ag]})

In [21]:
reg.predict(variables(3000,3,40))

array([444400.])

In [22]:
reg.predict(variables(2500,5,4))

array([569425.])