In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

In [5]:
digits=load_digits()
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [10]:
lr=LogisticRegression(max_iter=200)
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9592592592592593

In [11]:
svm=SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9925925925925926

In [12]:
rf=RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9777777777777777

In [13]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [14]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [15]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train,y_train)
    return model.score(X_test, y_test)

In [16]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)

In [56]:
scores_lr=[]
scores_svm=[]
scores_rf=[]

for train_index, test_index in folds.split(digits.data, digits.target):
    X_train, X_test, y_train, y_test=digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    scores_lr.append(get_score(LogisticRegression(max_iter=200), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(C=2), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=100), X_train, X_test, y_train, y_test))

In [57]:
scores_lr

[0.9198664440734557, 0.9415692821368948, 0.9165275459098498]

In [58]:
scores_svm

[0.9666110183639399, 0.9833055091819699, 0.9699499165275459]

In [59]:
scores_rf

[0.9365609348914858, 0.9599332220367279, 0.9248747913188647]

In [60]:
from sklearn.model_selection import cross_val_score

In [66]:
cross_val_score(LogisticRegression(max_iter=170),digits.data, digits.target)

array([0.92222222, 0.87222222, 0.94150418, 0.93871866, 0.89693593])

In [67]:
cross_val_score(SVC(C=2),digits.data, digits.target)

array([0.98055556, 0.94722222, 0.98328691, 0.98885794, 0.95264624])

In [71]:
cross_val_score(RandomForestClassifier(n_estimators=100),digits.data, digits.target)

array([0.94444444, 0.90833333, 0.9637883 , 0.96935933, 0.9275766 ])